/**
 * Database Seeder
 * Seeds static reference data: sia_codes (255 records), subscriptions (6 records).
 * Run with: node scripts/seed.js
 */
import 'dotenv/config';
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const SIA_CODES = [
  { code: 'AR', description: 'Ripristino Alimentazione' },
  { code: 'AT', description: 'Guasto Alimentazione' },
  { code: 'BA', description: 'Allarme Furto' },
  { code: 'BB', description: 'Zona Furto Esclusa' },
  { code: 'BC', description: 'Allarme Furto Cancellato' },
  { code: 'BH', description: 'Ripristino Allarme Furto' },
  { code: 'BJ', description: 'Ripristino Guasto Furto' },
  { code: 'BR', description: 'Ripristino Furto' },
  { code: 'BS', description: 'Supervisione Furto' },
  { code: 'BT', description: 'Guasto Furto' },
  { code: 'BU', description: 'Zona Furto Inclusa' },
  { code: 'BV', description: 'Furto Verificato' },
  { code: 'BX', description: 'Test Furto' },
  { code: 'CA', description: 'Inserimento Automatico' },
  { code: 'CE', description: 'Tempo Inserimento Esteso' },
  { code: 'CF', description: 'Sistema Inserito, alcune Zone non pronte.' },
  { code: 'CG', description: 'Sistema Inserito Parzialmente' },
  { code: 'CI', description: 'Inserimento Fallito' },
  { code: 'CJ', description: 'Inserimento in Ritardo' },
  { code: 'CK', description: 'Inserimento in Anticipo' },
  { code: 'CL', description: 'Inserimento Effettuato' },
  { code: 'CP', description: 'Inserimento Automatico' },
  { code: 'CR', description: 'Allarme dopo Inserimento' },
  { code: 'CS', description: 'Inserimento con Chiave' },
  { code: 'CT', description: "Disinserimento oltre il tempo d'Ingresso" },
  { code: 'CW', description: 'Inserimento Forzato' },
  { code: 'DC', description: 'Accesso Vietato' },
  { code: 'DD', description: 'Accesso Rifiutato' },
  { code: 'DF', description: 'Apertura Forzata' },
  { code: 'DG', description: 'Accesso Consentito' },
  { code: 'DK', description: 'Accesso non Consentito' },
  { code: 'DO', description: 'Accesso Consentito' },
  { code: 'DR', description: 'Anomalia Accesso Ripristinata' },
  { code: 'DS', description: 'Accesso' },
  { code: 'DT', description: 'Guasto Accesso' },
  { code: 'DU', description: 'ID Cliente' },
  { code: 'EA', description: 'Allarme Zona Uscita' },
  { code: 'EE', description: 'Allarme Zona Uscita' },
  { code: 'ER', description: 'Guasto Espansione' },
  { code: 'ET', description: 'Ripristino Espansione' },
  { code: 'FA', description: 'Allarme Incendio' },
  { code: 'FB', description: 'Zona Incendio Esclusa' },
  { code: 'FH', description: 'Ripristino Allarme Incendio' },
  { code: 'FI', description: 'Inizio Test Incendio' },
  { code: 'FJ', description: 'Ripristino Guasto Incendio' },
  { code: 'FK', description: 'Fine Test Incendio' },
  { code: 'FR', description: 'Ripristino Incendio' },
  { code: 'FS', description: 'Supervisione Indendio' },
  { code: 'FT', description: 'Guasto Incendio' },
  { code: 'FU', description: 'Zona Incendio Inclusa' },
  { code: 'FX', description: 'Test Incendio' },
  { code: 'GA', description: 'Allarme Gas' },
  { code: 'GB', description: 'Zona Gas Esclusa' },
  { code: 'GH', description: 'Ripristino Allarme Gas' },
  { code: 'GJ', description: 'Ripristino Guasto Gas' },
  { code: 'GR', description: 'Ripristino Gas' },
  { code: 'GS', description: 'Supervisione Gas' },
  { code: 'GT', description: 'Guasto Gas' },
  { code: 'GU', description: 'Zona Gas Inclusa' },
  { code: 'GX', description: 'Test Gas' },
  { code: 'HA', description: 'Allarme Rapina' },
  { code: 'HB', description: 'Zona Rapina Esclusa' },
  { code: 'HH', description: 'Ripristino Allarme Rapina' },
  { code: 'HJ', description: 'Ripristino Guasto Rapina' },
  { code: 'HR', description: 'Ripristino Rapina' },
  { code: 'HS', description: 'Supervisione Rapina' },
  { code: 'HT', description: 'Guasto Rapina' },
  { code: 'HU', description: 'Zona Rapina Inclusa' },
  { code: 'JA', description: 'Codice Utente a Rischio' },
  { code: 'JD', description: 'Data Aggiornata' },
  { code: 'JH', description: 'Programmazione Festività Aggiornata' },
  { code: 'JL', description: 'Soglia Eventi Raggiunta' },
  { code: 'JO', description: 'Overflow Soglia Eventi' },
  { code: 'JP', description: 'Riconosciuto PIN' },
  { code: 'JR', description: 'Programmatore Orario Eseguito' },
  { code: 'JS', description: 'Programmatore Orario Aggiornato' },
  { code: 'JT', description: 'Orario Aggiornato' },
  { code: 'JV', description: 'Codice Utente Aggiornato' },
  { code: 'JX', description: 'Codice Utente Cancellato' },
  { code: 'KA', description: 'Allarme Temperatura' },
  { code: 'KB', description: 'Zona Temperatura Esclusa' },
  { code: 'KH', description: 'Ripristino Allarme Temperatura' },
  { code: 'KJ', description: 'Ripristino Guasto Temperatura' },
  { code: 'KR', description: 'Ripristino Temperatura' },
  { code: 'KS', description: 'Supervisione Temperatura' },
  { code: 'KT', description: 'Guasto Temperatura' },
  { code: 'KU', description: 'Zona Temperatura Inclusa' },
  { code: 'LB', description: 'Programmazione Locale' },
  { code: 'LD', description: 'Programmazione locale Rifiutata' },
  { code: 'LE', description: 'Lettura eseguita' },
  { code: 'LF', description: 'Inizio Lettura' },
  { code: 'LR', description: 'Ripristio Linea Telefonica' },
  { code: 'LS', description: 'Scrittura Programmazione Eseguita' },
  { code: 'LT', description: 'Guasto Linea Telefonica' },
  { code: 'LU', description: 'Scrittura Programmazione Fallita' },
  { code: 'LX', description: 'Programmazione Locale Conclusa' },
  { code: 'MA', description: 'Allarme Medico' },
  { code: 'MB', description: 'Zona Medico Esclusa' },
  { code: 'MH', description: 'Ripristino Allarme Medico' },
  { code: 'MJ', description: 'Ripristino Guasto Medico' },
  { code: 'MR', description: 'Ripristino Medico' },
  { code: 'MS', description: 'Supervisione Medico' },
  { code: 'MT', description: 'Guasto Medico' },
  { code: 'MU', description: 'Zona Medico Inclusa' },
  { code: 'NA', description: 'Inattività' },
  { code: 'NF', description: 'Sensori non Pronti' },
  { code: 'NL', description: 'Perimetro Inserito' },
  { code: 'NR', description: 'Ripristino Guasto di Rete' },
  { code: 'NT', description: 'Guasto di Rete (GPRS o Ethernet)' },
  { code: 'OA', description: 'Sistema Disinserito Automaticamente' },
  { code: 'OG', description: 'Sistema Parzialmente Disinserito' },
  { code: 'OI', description: 'Autoinserimento Fallito' },
  { code: 'OJ', description: "Disinserimento oltre il tempo d'Ingresso" },
  { code: 'OK', description: 'Disinserimento in anticipo' },
  { code: 'OP', description: 'Disinserimento Effettuato' },
  { code: 'OT', description: 'Inserimento in ritardo' },
  { code: 'PA', description: 'Allarme Panico' },
  { code: 'PB', description: 'Zona Panico Esclusa' },
  { code: 'PH', description: 'Ripristino Allarme Panico' },
  { code: 'PJ', description: 'Ripristino Guasto Panico' },
  { code: 'PR', description: 'Ripristino Panico' },
  { code: 'PS', description: 'Supervisione Panico' },
  { code: 'PT', description: 'Guasto Panico' },
  { code: 'PU', description: 'Zona Panico Inclusa' },
  { code: 'QA', description: 'Allarme Emergenza' },
  { code: 'QB', description: 'Zona Emergenza Esclusa' },
  { code: 'QH', description: 'Ripristino Allarme Emergenza' },
  { code: 'QJ', description: 'Ripristino Guasto Emergenza' },
  { code: 'QR', description: 'Ripristino Emergenza' },
  { code: 'QS', description: 'Supervisione Emergenza' },
  { code: 'QT', description: 'Guasto Emergenza' },
  { code: 'QU', description: 'Zona Emergenza Inclusa' },
  { code: 'RA', description: 'Programmazione da Remoto Fallita' },
  { code: 'RB', description: 'Programmazione da Remoto' },
  { code: 'RC', description: 'Relay Attivato' },
  { code: 'RD', description: 'Programmazione da Remoto Rifiutata' },
  { code: 'RG', description: 'Lettore Sbloccato' },
  { code: 'RL', description: 'Lettore Bloccato' },
  { code: 'RN', description: 'Reset da remoto' },
  { code: 'RO', description: 'Relay Disattivato' },
  { code: 'RP', description: 'Test Automatico' },
  { code: 'RR', description: 'Ripristino Alimentazione' },
  { code: 'RS', description: 'Programmazione da Remoto Eseguita' },
  { code: 'RT', description: 'Data Lost' },
  { code: 'RU', description: 'Programmazione da Remoto Fallita' },
  { code: 'SA', description: 'Allarme Sprinkler' },
  { code: 'SB', description: 'Zona Sprinkler Esclusa' },
  { code: 'SH', description: 'Ripristino Allarme Sprinkler' },
  { code: 'SJ', description: 'Ripristino Guasto Sprinkler' },
  { code: 'SR', description: 'Ripristino Sprinkler' },
  { code: 'SS', description: 'Supervisione Sprinkler' },
  { code: 'ST', description: 'Guasto Sprinkler' },
  { code: 'SU', description: 'Zona Sprinkler Inclusa' },
  { code: 'TA', description: 'Allarme Tamper' },
  { code: 'TB', description: 'Zona Tamper Esclusa' },
  { code: 'TC', description: 'Fine Walktest' },
  { code: 'TE', description: 'Test Finito' },
  { code: 'TP', description: 'Zona Testata' },
  { code: 'TR', description: 'Ripristino Tamper' },
  { code: 'TS', description: 'Test Iniziato' },
  { code: 'TU', description: 'Zona Tamper Inclusa' },
  { code: 'TX', description: 'Report Test' },
  { code: 'UA', description: 'Allarme Zona Sconosciuta' },
  { code: 'UB', description: 'Zona Sconosciuta Esclusa' },
  { code: 'UH', description: 'Ripristino Allarme Zona Sconosciuta' },
  { code: 'UJ', description: 'Ripristino Guasto Zona Sconosciuta' },
  { code: 'UR', description: 'Zona Sconosciuta Tamper' },
  { code: 'US', description: 'Supervisione Zona Sconosciuta' },
  { code: 'UT', description: 'Guasto Zona Sconosciuta' },
  { code: 'UU', description: 'Zona Sconosciuta Inclusa' },
  { code: 'UX', description: 'Indefinito' },
  { code: 'VR', description: 'Ripristino Stampante' },
  { code: 'VT', description: 'Guasto Stampante' },
  { code: 'VX', description: 'Test Stampante' },
  { code: 'VY', description: 'Stampante Online' },
  { code: 'VZ', description: 'Stampante Offline' },
  { code: 'WA', description: 'Allarme Allagamento' },
  { code: 'WB', description: 'Zona Allagamento Esclusa' },
  { code: 'WH', description: 'Ripristino Allarme Allagamento' },
  { code: 'WJ', description: 'Ripristino Guasto Allagamento' },
  { code: 'WR', description: 'Ripristino Allagamento' },
  { code: 'WS', description: 'Supervisione Allagamento' },
  { code: 'WT', description: 'Guasto Allagamento' },
  { code: 'WU', description: 'Zona Allagamento Inclusa' },
  { code: 'XD', description: 'Basso Valore Tensione' },
  { code: 'XE', description: 'Extra Point' },
  { code: 'XF', description: 'Extra RF Point' },
  { code: 'XG', description: 'Ripristino Basso Valore Tensione' },
  { code: 'XH', description: 'Ripristino Jamming RF' },
  { code: 'XI', description: 'Reset Sensore' },
  { code: 'XJ', description: 'Ripristino Tamper RF' },
  { code: 'XQ', description: 'Guasto Jamming RF' },
  { code: 'XR', description: 'Ripristino Batteria Trasmettitore' },
  { code: 'XS', description: 'Tamper RF' },
  { code: 'XT', description: 'Guasto Batteria Trasmettitore' },
  { code: 'YA', description: 'Guasto Sirena' },
  { code: 'YC', description: 'Fallimento Comunicazione' },
  { code: 'YF', description: 'Aggiornamento Data' },
  { code: 'YG', description: 'Aggiornamento Eseguito' },
  { code: 'YH', description: 'Ripristino Sirena' },
  { code: 'YI', description: 'Inizio Manutenzione' },
  { code: 'YJ', description: 'Fine Manutenzione' },
  { code: 'YK', description: 'Ripristino Comunicazione' },
  { code: 'YM', description: 'Batteria Trasmettitore Assente' },
  { code: 'YN', description: 'Report Fallito' },
  { code: 'YO', description: 'Messaggio Sconosciuto' },
  { code: 'YP', description: 'Guasto Alimentazione' },
  { code: 'YQ', description: 'Ripristino Alimentazione' },
  { code: 'YR', description: 'Ripristino Batteria Sistema' },
  { code: 'YS', description: 'Guasto Comunicazione' },
  { code: 'YT', description: 'Guasto Batteria Sistema' },
  { code: 'YW', description: 'Reset Watchdog' },
  { code: 'YX', description: 'Service Richiesto' },
  { code: 'YY', description: 'Status Report' },
  { code: 'YZ', description: 'Service Completo' },
  { code: 'ZA', description: 'Allarme Tecnologico' },
  { code: 'ZB', description: 'Zona Gelo Esclusa' },
  { code: 'ZC', description: 'Zona a Riposo' },
  { code: 'ZH', description: 'Ripristino Allarme Gelo' },
  { code: 'ZJ', description: 'Ripristino Guasto Gelo' },
  { code: 'ZK', description: 'Inizio Walktest' },
  { code: 'ZM', description: 'Zona in Accecamento' },
  { code: 'ZO', description: 'Zona Aperta' },
  { code: 'ZR', description: 'Ripristino Tecnologico' },
  { code: 'ZS', description: 'Supervisione Gelo' },
  { code: 'ZT', description: 'Guasto Gelo' },
  { code: 'ZU', description: 'Zona Gelo Inclusa' },
  { code: 'ZX', description: 'Zona in C.C.' },
  { code: 'AU', description: 'Tessera Sconosciuta' },
  { code: 'CU', description: 'Ripristino telecamera' },
  { code: 'CV', description: 'Disconnessione Telecamera' },
  { code: 'DI', description: 'Accesso Negato da Anti-Passback' },
  { code: 'DN', description: 'Porta rimasta Aperta' },
  { code: 'EJ', description: 'Ripristino Tamper Espansione' },
  { code: 'EM', description: 'Scomparsa Espansione' },
  { code: 'EN', description: 'Ripristino Scomparsa Espansione' },
  { code: 'ES', description: 'Tamper Espansione' },
  { code: 'FC', description: 'Allarme Incendio Cancellato' },
  { code: 'KG', description: 'Tastiera Sbloccata' },
];

const SUBSCRIPTIONS = [
  { id: 1, code: 'Free-Lite', description: 'Relax Lite - Primo Anno', daysDuration: 365 },
  { id: 2, code: 'Free-Pro', description: 'Relax Pro - Primo Anno', daysDuration: 365 },
  { id: 3, code: 'Lite1Y', description: 'Relax Lite - Annuale', daysDuration: 365 },
  { id: 4, code: 'Pro1Y', description: 'Relax Pro - Annuale', daysDuration: 365 },
  { id: 5, code: 'Lite3Y', description: 'Relax Lite - 3 Anni', daysDuration: 1095 },
  { id: 6, code: 'Pro3Y', description: 'Relax Pro - 3 Anni', daysDuration: 1095 },
];

async function main() {
  console.log('🌱 Seeding database...');

  // Seed SIA codes (upsert to avoid duplicates)
  console.log(`Seeding ${SIA_CODES.length} SIA codes...`);
  for (const code of SIA_CODES) {
    await prisma.siaCode.upsert({
      where: { code: code.code },
      create: code,
      update: { description: code.description },
    });
  }

  // Seed subscriptions
  console.log(`Seeding ${SUBSCRIPTIONS.length} subscription plans...`);
  for (const sub of SUBSCRIPTIONS) {
    await prisma.subscription.upsert({
      where: { id: sub.id },
      create: sub,
      update: sub,
    });
  }

  // Initialize statistics row
  const existing = await prisma.statistic.findFirst();
  if (!existing) {
    await prisma.statistic.create({
      data: { keepAlives: BigInt(0), alarms: BigInt(0) },
    });
    console.log('Created statistics row');
  }

  console.log('✅ Seeding complete!');
}

main()
  .catch((err) => {
    console.error('Seed failed:', err);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
